export {
    MasterProvince,
    MasterAmphur,
    MasterDistrict,
    MasterSourceType,
    MasterChannelType,
    MasterBusinessType,
    MasterInterestingProduct,
    MasterOpportunityCustomer,
    MasterPresentProductType,
    MasterBusinessPrefix,
    MasterAppointmentReason,
    MasterPrefix,

    MasterBranchTemporary,
    MasterRegion,
    MasterArea,
    MasterBranch,
    MasterTargetMarketProvince,
    GetNanoMarkerMap,
    GetNanoMarketInformation,
    GetNanoBranchInformation,
    GetNanoCAInformation,
    GetNanoComplititorProvince,
    GetNanoComplititor,

    GetNanoProductPerformance,
    GetNanoTotalSummary,
    GetNanoGroupBySummary
} from './master'