import { combineReducers } from 'redux'
import { routerReducer } from 'react-router-redux'
import { MASTER_ALL } from './master'
import { AUTH } from './login'
import {
    AUTH_NANO_USER,
    NANO_MASTER_ALL,
    NANO_INIT_PAGE,

    ON_NANO_SEARCHING_DATA,
    ON_NANO_CHANGE_VIEW_SEARCHING_DATA,
    NANO_FILTER_CRITERIA,
    SELECTED_CA_MAP,
    DO_BOUNDS_MAP,
    RELATED_BRANCH_DATA,
    RELATED_EXITING_MARKET_DATA,
    RELATED_EXITING_MARKET_DATA_BACKUP,
    RELATED_TARGET_MARKET_DATA,
    RELATED_CA_IN_MARKET_DATA,
    RELATED_CA_NOTE_DATA,
    RELATED_PLAN_OPEN_BRANCH_DATA,
    RELATED_PERFORMANCE_SUMMARY_DATA,
    RELATED_OVERALL_SUMMARY_DATA,
    RELATED_GROUP_BY_SUMMARY_DATA,
    RELATED_GROUP_BY_MARKET_SUMMARY_DATA,
    RELATED_COMPLITITOR_DATA,
    CA_SUMMARY_ONLY_MARKET_PENETRATION,
    CA_SUMMARY_ONLY_MARKET_CONTRIBUTION,
    RELATED_CHART_PORTFOLIO_QUALITY,
    CHART_PORTFOLIO_QUALITY_BY_CA,
    RELATED_CHART_SALE_SUMMARY,
    CHART_SALE_SUMMARY_BY_CA,
    NANO_VISIT_POPUP_INFO,
    NANO_VISIT_POPUP_STATUS,
    NANO_BRANCH_DIRECTION_DATA,
    NANO_BRANCH_DIRECTION_NOTE_DATA,
    NANO_BRANCH_DIRECTION_DATA_STATUS,
    NANO_BRANCH_DIRECTION_NOTE_STATUS,

    GLOBAL_POPOVER_STATE
} from './nanomaster'

export default combineReducers({
    routing: routerReducer,
    AUTH: AUTH,
    MASTER_ALL: MASTER_ALL,

    AUTH_NANO_USER,
    NANO_MASTER_ALL,
    NANO_INIT_PAGE,

    ON_NANO_SEARCHING_DATA,
    ON_NANO_CHANGE_VIEW_SEARCHING_DATA,
    NANO_FILTER_CRITERIA,
    SELECTED_CA_MAP,
    DO_BOUNDS_MAP,
    RELATED_BRANCH_DATA,
    RELATED_EXITING_MARKET_DATA,
    RELATED_EXITING_MARKET_DATA_BACKUP,
    RELATED_TARGET_MARKET_DATA,
    RELATED_CA_IN_MARKET_DATA,
    RELATED_CA_NOTE_DATA,
    RELATED_PLAN_OPEN_BRANCH_DATA,
    RELATED_PERFORMANCE_SUMMARY_DATA,
    RELATED_OVERALL_SUMMARY_DATA,
    RELATED_GROUP_BY_SUMMARY_DATA,
    RELATED_GROUP_BY_MARKET_SUMMARY_DATA,
    RELATED_COMPLITITOR_DATA,
    CA_SUMMARY_ONLY_MARKET_PENETRATION,
    CA_SUMMARY_ONLY_MARKET_CONTRIBUTION,
    RELATED_CHART_PORTFOLIO_QUALITY,
    CHART_PORTFOLIO_QUALITY_BY_CA,
    RELATED_CHART_SALE_SUMMARY,
    CHART_SALE_SUMMARY_BY_CA,
    NANO_VISIT_POPUP_INFO,
    NANO_VISIT_POPUP_STATUS,

    NANO_BRANCH_DIRECTION_DATA,
    NANO_BRANCH_DIRECTION_NOTE_DATA,
    NANO_BRANCH_DIRECTION_DATA_STATUS,
    NANO_BRANCH_DIRECTION_NOTE_STATUS,

    GLOBAL_POPOVER_STATE
})
