export const ON_OPEN_MAIN_MENU = 'ON_OPEN_MAIN_MENU'
export const ON_DRAG_EVENT_CALENDAR = 'ON_DRAG_EVENT_CALENDAR'

export const LOAD_CALENDAR_MASTER_EVENTS_REQUEST = 'LOAD_CALENDAR_MASTER_EVENTS_REQUEST'
export const LOAD_CALENDAR_MASTER_EVENTS_SUCCESS = 'LOAD_CALENDAR_MASTER_EVENTS_SUCCESS'
export const LOAD_CALENDAR_MASTER_EVENTS_FAILED = 'LOAD_CALENDAR_MASTER_EVENTS_FAILED'

export const LOAD_CALENDAR_EVENT_REQUEST = 'LOAD_CALENDAR_EVENT_REQUEST'
export const LOAD_CALENDAR_EVENT_SUCCESS = 'LOAD_CALENDAR_EVENT_SUCCESS'
export const LOAD_CALENDAR_EVENT_FAILED = 'LOAD_CALENDAR_EVENT_FAILED'

export const INSERT_CALENDAR_EVENT_REQUEST = 'INSERT_CALENDAR_EVENT_REQUEST'
export const INSERT_CALENDAR_EVENT_SUCCESS = 'INSERT_CALENDAR_EVENT_SUCCESS'
export const INSERT_CALENDAR_EVENT_FAILED = 'INSERT_CALENDAR_EVENT_FAILED'

export const UPDATE_CALENDAR_EVENT_REQUEST = 'UPDATE_CALENDAR_EVENT_REQUEST'
export const UPDATE_CALENDAR_EVENT_SUCCESS = 'UPDATE_CALENDAR_EVENT_SUCCESS'
export const UPDATE_CALENDAR_EVENT_FAILED = 'UPDATE_CALENDAR_EVENT_FAILED'

export const DELETE_CALENDAR_EVENT_REQUEST = 'DELETE_CALENDAR_EVENT_REQUEST'
export const DELETE_CALENDAR_EVENT_SUCCESS = 'DELETE_CALENDAR_EVENT_SUCCESS'
export const DELETE_CALENDAR_EVENT_FAILED = 'DELETE_CALENDAR_EVENT_FAILED'
