export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const MASTER_ALL_SUCCESS = 'MASTER_ALL_SUCCESS'

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE'


//----------------------------- Nano -------------------------------
export const LOAD_NANO_MASTER_ALL_REQUEST = 'LOAD_NANO_MASTER_ALL_REQUEST'
export const LOAD_NANO_MASTER_ALL_SUCCESS = 'LOAD_NANO_MASTER_ALL_SUCCESS'
export const LOAD_NANO_MASTER_ALL_FAILURE = 'LOAD_NANO_MASTER_ALL_FAILURE'

export const SET_FILTER_CRITERIA_REQUEST = 'SET_FILTER_CRITERIA_REQUEST'
export const SET_OPEN_BRANCH_MARKER_REQUEST = 'SET_OPEN_BRANCH_MARKER_REQUEST'
export const SET_OPEN_EXITING_MARKET_MARKER_REQUEST = 'SET_OPEN_EXITING_MARKET_MARKER_REQUEST'
export const SET_OPEN_TARGET_MARKET_MARKER_REQUEST = 'SET_OPEN_TARGET_MARKET_MARKER_REQUEST'
export const SEARCH_NANO_DATA_REQUEST = 'SEARCH_NANO_DATA_REQUEST'
export const SEARCH_NANO_DATA_SUCCESS = 'SEARCH_NANO_DATA_SUCCESS'
export const SEARCH_NANO_DATA_FAILURE = 'SEARCH_NANO_DATA_FAILURE'

export const SEARCH_NANO_CHANGE_VIEW_DATA_REQUEST = 'SEARCH_NANO_CHANGE_VIEW_DATA_REQUEST'
export const SEARCH_NANO_CHANGE_VIEW_DATA_SUCCESS = 'SEARCH_NANO_CHANGE_VIEW_DATA_SUCCESS'
export const SEARCH_NANO_CHANGE_VIEW_DATA_FAILURE = 'SEARCH_NANO_CHANGE_VIEW_DATA_FAILURE'

export const CHANGE_MAP_MARKER_BY_CA = 'CHANGE_MAP_MARKER_BY_CA'

export const INSERT_MARKER_NOTE_REQUEST = 'INSERT_MARKER_NOTE_REQUEST'
export const INSERT_MARKER_NOTE_SUCCESS = 'INSERT_MARKER_NOTE_SUCCESS'
export const INSERT_MARKER_NOTE_FAILURE = 'INSERT_MARKER_NOTE_FAILURE'

export const DELETE_MARKER_NOTE_REQUEST = 'DELETE_MARKER_NOTE_REQUEST'
export const DELETE_MARKER_NOTE_SUCCESS = 'DELETE_MARKER_NOTE_SUCCESS'
export const DELETE_MARKER_NOTE_FAILURE = 'DELETE_MARKER_NOTE_FAILURE'

export const SET_MARKER_NOTE_DEFAULT_REQUEST = 'SET_MARKER_NOTE_DEFAULT_REQUEST'
export const SET_MARKER_NOTE_DEFAULT_SUCCESS = 'SET_MARKER_NOTE_DEFAULT_SUCCESS'
export const SET_MARKER_NOTE_DEFAULT_FAILURE = 'SET_MARKER_NOTE_DEFAULT_FAILURE'

export const GET_CA_SUMMARY_ONLY_REQUEST = 'GET_CA_SUMMARY_ONLY_REQUEST'
export const GET_CA_SUMMARY_ONLY_SUCCESS = 'GET_CA_SUMMARY_ONLY_SUCCESS'
export const GET_CA_SUMMARY_ONLY_FAILURE = 'GET_CA_SUMMARY_ONLY_FAILURE'