export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const MASTER_ALL_SUCCESS = 'MASTER_ALL_SUCCESS'

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE'


//----------------------------- Nano -------------------------------
export const LOAD_NANO_MASTER_ALL_REQUEST = 'LOAD_NANO_MASTER_ALL_REQUEST'
export const LOAD_NANO_MASTER_ALL_SUCCESS = 'LOAD_NANO_MASTER_ALL_SUCCESS'
export const LOAD_NANO_MASTER_ALL_FAILURE = 'LOAD_NANO_MASTER_ALL_FAILURE'

export const SET_FILTER_CRITERIA_REQUEST = 'SET_FILTER_CRITERIA_REQUEST'
export const SET_OPEN_BRANCH_MARKER_REQUEST = 'SET_OPEN_BRANCH_MARKER_REQUEST'
export const SET_OPEN_EXITING_MARKET_MARKER_REQUEST = 'SET_OPEN_EXITING_MARKET_MARKER_REQUEST'
export const SET_OPEN_TARGET_MARKET_MARKER_REQUEST = 'SET_OPEN_TARGET_MARKET_MARKER_REQUEST'
export const SEARCH_NANO_DATA_REQUEST = 'SEARCH_NANO_DATA_REQUEST'
export const SEARCH_NANO_DATA_SUCCESS = 'SEARCH_NANO_DATA_SUCCESS'
export const SEARCH_NANO_DATA_FAILURE = 'SEARCH_NANO_DATA_FAILURE'

export const SEARCH_NANO_CHANGE_VIEW_DATA_REQUEST = 'SEARCH_NANO_CHANGE_VIEW_DATA_REQUEST'
export const SEARCH_NANO_CHANGE_VIEW_DATA_SUCCESS = 'SEARCH_NANO_CHANGE_VIEW_DATA_SUCCESS'
export const SEARCH_NANO_CHANGE_VIEW_DATA_FAILURE = 'SEARCH_NANO_CHANGE_VIEW_DATA_FAILURE'

export const CHANGE_MAP_MARKER_BY_CA = 'CHANGE_MAP_MARKER_BY_CA'